### ISSUE TITLE
Resnet18 Architecture

### ISSUE THREAD

**Issue by mmderakhshani** [arslan-chaudhry/orthog_subspace#2]
hi @arslan-chaudhry,

Thanks for providing your source code. could you please tell me, did you use the exact resnet18 architecture or the smaller version of it, let's say it in terms of kernel size or the number of filters?

Thanks.

**Comment by arslan-chaudhry** [comment]
We used the standard ResNet-18 (exact, as you called it). See section 4.3 in the paper or code for reference.

**Comment by mmderakhshani** [comment]
Thanks. Because I found that in the continual learning experimental setting, people use a smaller version of it. Anyway! Thanks.
