### ISSUE TITLE
Resize for orthogonal matrix

### ISSUE THREAD

**Issue by leondada** [arslan-chaudhry/orthog_subspace#3]
hi, it's an interesting work, can you tell me the details of this sentence?  
`"For example, to make space for 2T tasks one can resize the original matrix to 2m × 2m with zero padding, and backup the previous matrix."`
I am not sure about the meaning of "original matrix" and "previous matrix", when the total number of tasks exceeds T, how can you give enough basis to form O_t?

**Comment by leondada** [comment]
one more thing, when we do test on a new task, how can we know which matrix P should we use?

**Comment by arslan-chaudhry** [comment]
Say your original feature space was m-dimensional for the first T tasks. Each projection matrix P_t was m X m dimensional. When the tasks exceed T, you would extend the feature space to 2m and append 0's to the projection matrices from {1, ..., T} such that you would get 2m x 2m matrices (creating space for the next T tasks) with the original matrices backed in the first m x m diagonal block (and 0's elsewhere). The space from the remaining main diagonal block i.e. from rows m+1 to 2m and columns m+1 to 2m would be used for tasks {T+1, ..., 2T}. 
At test time, we provide the projection matrix along with the task id.

**Comment by leondada** [comment]
got it!  thank you very much
